module.exports = {
  MIN_DICE: 0,
  MAX_DICE: 20,
  MAX_DIE_SIZE: 12,
  MIN_DIE_SIZE: 0,
  MIN_INFORMATION: 4,
  MAX_INFORMATION: 50,
  MIN_DESCRIPTION: 8,
  MAX_DESCRIPTION: 500,
  MAX_LEGENDARY_RESISTANCES: 4,
  MAX_SPELL_SLOTS: 4,
};
